os: linux
language: cpp

dist: bionic

compiler:
    - gcc
    - clang

branches:
    only: 
    - /.*/

before_install:
    - sudo apt-get update

install:
    # OpenCV dependencies
    - sudo apt-get -y install build-essential libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev

before_script:
    - ./install_opencv.sh
    
script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build  . 
