os: linux
language: cpp

dist: bionic

compiler:
    - gcc
    - clang

branches:
    only: 
    - /.*/

before_install:
    - sudo apt-get update

install:
    # OpenCV dependencies
    - sudo apt-get -y install build-essential libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev
    # Cinder dependencies
    - sudo apt-get -y install libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev zlib1g-dev libfontconfig1-dev libmpg123-dev libsndfile1 libsndfile1-dev libpulse-dev libasound2-dev libcurl4-gnutls-dev libgstreamer1.0-dev libgstreamer-plugins-bad1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-libav gstreamer1.0-alsa gstreamer1.0-pulseaudio gstreamer1.0-plugins-bad libboost-filesystem-dev

before_script:
    - ./install_opencv.sh
    
script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build  . 
